{% set name = "opentelemetry-instrumentation-asgi" %}
{% set version = "0.37b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_asgi-{{ version }}.tar.gz
  sha256: b8557d8823a04e083aae18f285a4c2ed75746acf9f2e63e44778f2aa8942af02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - asgiref ~=3.0
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.37b0
    - opentelemetry-semantic-conventions ==0.37b0
    - opentelemetry-util-http ==0.37b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-asgi 

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asgi
  summary: ASGI instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
