{% set name = "opentelemetry-instrumentation-asgi" %}
{% set version = "0.42b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_asgi-{{ version }}.tar.gz
  sha256: da1d5dd4f172c44c6c100dae352e1fd0ae36dc4f266b3fed68ce9d5ab94c9146

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - asgiref ~=3.0
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.42b0
    - opentelemetry-semantic-conventions ==0.42b0
    - opentelemetry-util-http ==0.42b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-asgi 
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-asgi 
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-asgi 
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-asgi 
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-asgi 
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-asgi 

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asgi
  summary: ASGI instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
